export { setQuestion,
         setAnswer,
         setQuestions,
         setAnswers,
         setQuestionDialog,
         setErrorText,
         setCurrentQuestion,
         setCurrentView,
         setCurrentUser,
         setMapMarkers,
         setQuestionsInView } from './questionBoardActions';


export { setHousing,
         setCol,
         setHealthcare,
         setEnvironmentalQuality,
         setEconomy,
         setLeisure,
         setCommute,
         setSafety,
         setEducation,
         setSummary,
         setTravelConnectivity,
         setInternetAccess,
         setTolerance,
         setOutdoors,
         setTaxation,
         setBusinessFreedom,
         setStartUps,
         setVentureCapital,
         setPhotoURL,
         setCity, 
         setScore } from './cityInfoActions';

export { setCurrentLocation } from './profileActions';
